name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Test Formatting
        run: |
          test "0" = $(gofmt -l .| wc -l)
      - name: Test with race and coverage
        timeout-minutes: 1
        run: |
          go test -race -covermode=atomic -covermode=atomic